# Generated by Django 3.2.7 on 2021-10-09 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='todo',
        ),
    ]
